name: Upgrade SQLite and Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  upgrade-sqlite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and upgrade system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Verify SQLite version
        run: sqlite3 --version

      - name: Clear pip cache  # 添加清理 pip 缓存步骤
        run: |
          pip cache purge  # 清理 pip 缓存

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 安装 requirements 中的依赖
